

default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

      firebase_app_distribution(
    app: "1:552861192831:android:c856ea2dd1f617eda8e54a",
    firebase_cli_token:ENV ["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "esafm636@gmail.com",
    release_notes: "Second Fastlane Firebase Distribution"
  )
  end
end
